language: php
php:
  - 7.1

sudo: required
dist: trusty

services:
    - docker

cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $HOME/.npm
    - /tmp/phantomjs
    - tools

env:
  global:
    - CORE_BRANCH=stable16
    - APP_NAME=guests
  matrix:
    - DB=sqlite

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server
  - docker pull mailhog/mailhog
  - docker run -d -i -p 8025:8025 -p 1025:1025 -t mailhog/mailhog

  # Add some output debugging information
  - ./occ check
  - ./occ status
  - ./occ app:list

script:
  - cd apps/$APP_NAME/tests/integration
  - ./run.sh

