language: php
php:
  - 7.3

services:
  - postgresql
  - mysql

env:
  global:
  - APP_NAME=guests
matrix:
  include:
    - env: CORE_BRANCH=stable16 DB=sqlite
    - env: CORE_BRANCH=stable17 DB=sqlite
      php: 7.1
    - env: CORE_BRANCH=stable17 DB=sqlite
      php: 7.2
    - env: CORE_BRANCH=stable17 DB=sqlite
      php: 7.3
    - env: CORE_BRANCH=stable17 DB=mysql
    - env: CORE_BRANCH=stable17 DB=pgsql
    - env: CORE_BRANCH=master DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
  - cd ../
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH nextcloud
  - mv $APP_NAME nextcloud/apps/

before_script:
  # fill nextcloud with default configs and enable the app
  - cd nextcloud
  - mkdir data
  - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - ./occ app:enable $APP_NAME
  - cd apps/$APP_NAME
  - composer install

script:
  # check syntax
  - vendor/bin/parallel-lint --exclude app --exclude vendor --exclude tests .
  # Run phpunit tests
  - cd tests
  - ../vendor/bin/phpunit --configuration phpunit.xml
  # build js
  - npm install
  - npm run build

